from odoo import api, models, modules,fields, models

class IBEDC11KVFeeder(models.Model):
    _name = 'ibedc_11kv_feeder.model'
    f11kv_feeder_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    f11kvfeeder_name = fields.Char(string='F11kvFeeder Name')
    feeder_CBSerial = fields.Char(string='Feeder CBSerial')
    f11kvfeeder_cbyearofmanufacture = fields.Integer(string='CB Year of Manufacture')
    f11kvfeeder_CB_Make = fields.Char(string='CB Make') 
    f11kvfeeder_CB_country_of_Manufacture = fields.Char(string='CB country of Manufacture')
    f11kvfeeder_Relay_Make = fields.Char(string='F11kv Relay Make')
    f11kvfeeder_Relay_Type = fields.Char(string='F11kv Relay Type')
    f11kvfeeder_CTRatio = fields.Char(string='F11kv CT Ratio')
    f11kvfeeder_RMUSerial = fields.Char(string='F11kv RMU Serial')
    f11kvfeeder_RMUYearofManufacture = fields.Integer(string='F11kv RMU Year of Manufacture')
    f11kvfeeder_RMU_Make = fields.Char(string='F11kv RMU Make')
    f11kvfeeder_RMU_country_of_Manufacture = fields.Char(string='RMU country of Manufacture')
    f11kvfeeder_RMU_Type = fields.Char(string='F11kv RMU Type')
    f11kvfeeder_Route_Length = fields.Char(string='F11kv Route Length')
    f11kvfeeder_Conductor_Size = fields.Char(string='F11kv Conductor Size')
    f11kvfeeder_Aluminium_Conductor = fields.Char(string='F11kv Aluminium Conductor')
    f11kvfeeder_UP_Type = fields.Char(string='F11kv UP Type')
    f11kvfeeder_UP_Length = fields.Char(string='F11kv UP Length')
    f11kvfeeder_Manufacture = fields.Integer(string='F11kv Manufacture') 
    f11kvfeeder_Ratedcurrent = fields.Char(string='F11kv Ratedcurrent')
    f11kvfeeder_Ratedvoltage = fields.Char(string='F11kv Ratedvoltage')
    f11kvfeeder_CB_Type = fields.Char(string='F11kv CB_Type')
    # F11kv Aluminium Conductor F11kv Aluminium Conductor
    

class IBEDC132KVTransmissionSubstation(models.Model):
    _name = 'ibedc_32kvtransmission_substation.model'
    # f11kv_feeder_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    ts_132kv_name = fields.Float(string='TS 132KV Name')
    ts_132kv_rating = fields.Char(string='TS 132KV Rating')
    

class IBEDC33KVFeeder(models.Model):
    _name = 'ibedc_33kv_feeder.model'
    f33kv_feeder_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    f33kv_regional_name = fields.Char(string='F33kv Regional Name')
    f33kv_business_hub_name = fields.Char(string='Business Hub Name')
    f33kv_feeder_name = fields.Char(string='F33kv Feeder Name')
    f33kv_feeder_circuit_breaker_make = fields.Char(string='Feeder Circuit Breaker Make')
    f33kv_feeder_circuit_breaker_type = fields.Char(string='Feeder Circuit Breaker Type')
    f33kv_upriser_cable_type = fields.Char(string='Upriser Cable Type')
    f33kv_teeoffs = fields.Char(string='F33kv Teeoffs')
    f33kv_tee_offs_coordinate = fields.Char(string='F33kv Teeoffs Coordinate')
    f33kv_substations_capacity = fields.Char(string='F33kv Substations Capacity')
    f33kv_lineload_coordinate = fields.Char(string='F33kv Lineload Coordinate')
    f33kv_conductor_size = fields.Char(string='F33kv Conductor Size')
    f33kv_aluminium_conductor = fields.Char(string='F33kv Aluminium Conductor')
    f33kv_commisioning = fields.integer(string='F33kv Commisioning')


class Aindex(models.Model):
    _name = 'ibedc_33kv_feeder.model'
    cin = fields.Char(string='Customer Index Number')
    
class AssetPix(models.Model):
    _name = 'assetpix.model'
    
    assetid = fields.Char(string='Asset id')
    pix_no = fields.integer(string='Pix no')
    pix_label = fields.Char(string='Label')
    thepix = fields.Binary(string='Pix')
    
class AssetUpdate(models.Model):
    _name = 'assetupdate.model'
    
    updateid = fields.Char(string='Update id')
    assetid = fields.Char(string='Asset id')
    mode = fields.Char(string='Mode')
    unit = fields.Char(string='Unit')
    action_scope = fields.Char(string='Action Scope')
    action_scopeid = fields.Char(string='Action Scope id')
    action_role = fields.Char(string='Action Role')
    update_datetime = fields.Char(string='Update Datetime')
    review_scope = fields.Char(string='Review Scope')
    review_scopeid = fields.Char(string='Review Scope id')
    review_role = fields.Char(string='Review Role')
    review_device_datetime = fields.Char(string='Review Device Datetime')
    review_decision = fields.Char(string='Review Decision')
    review_comment = fields.Char(string='Review Comment')
    reviewed_by = fields.Char(string='Reviewed by')
    review_datetime = fields.Char(string='Review Datetime')
    approval_scope = fields.Char(string='Approval Scope')
    approval_scopeid = fields.Char(string='Approval Scope id')
    approval_role = fields.Char(string='Approval Role')
    approval_device_datetime= fields.Char(string='Approval Device Datetime')
    approval_decision = fields.Char(string='Approval Decision')
    approval_comment = fields.Char(string='Approval Comment')
    approval_by = fields.Char(string='Approval by')
    approval_datetime = fields.Char(string='Approval Datetime')
    

class AssetBuildings(models.Model):
    _name = 'buildings.model'
    
    assetid = fields.Char(string='Asset id')
    naccodes = fields.Binary(string='Naccodes')
    buildings_landlord_name = fields.Char(string='Landlord Name')
    buildings_landlord_phone = fields.Char(string='landlord phone')
    buildings_landlord_email = fields.Char(string='landlord email')
    buildings_landlord_occupation= fields.Char(string='Landlord Occupation')
    buildings_address = fields.Char(string='Address') 
    buildings_add_desc = fields.Char(string='add desc')
    buildings_addr_type = fields.Char(string='Address Type')
    buildings_status = fields.Char(string='Status')
    buildings_landmark = fields.Char(string='Landmark')
    buildings_category = fields.Char(string='Category')
    buildings_type = fields.Char(string='Type')
    buildings_floors = fields.Char(string='Floors')
    buildings_customer_no = fields.Char(string='Customer Number')
    buildings_any_other_remark = fields.Char(string='Other remarks')
    buildings_town = fields.Char(string='Town')
    buildings_lga = fields.Char(string='Local govt')
    buildings_state = fields.Char(string='State')
    buildings_service_centre = fields.Char(string='Service Center')
    buildings_fully_enumerated = fields.Char(string='Fully Enumerated')
    buildings_house_no = fields.Char(string='House no')
    buildings_street_name = fields.Char(string='Street Name')
    

class CallBack(models.Model):
    _name = 'callback.model'
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    callback_address = fields.Char(string='Callback Address')
    callback_add_desc= fields.Char(string='Callback Add desc') 
    callback_landmark = fields.Char(string='Callback Landmark')
    callback_remark = fields.Char(string='Callback Remark')
    

class CustomerQr(models.Model):
    _name = 'customerqr.model'
    
    assetid = fields.Char(string='Asset id')
    cust_has_account_no = fields.Char(string='cust has account_no')
    cust_account_no = fields.Char(string='cust_account_no')
    cust_has_meter_no = fields.Char(string='cust_has_meter_no')
    cust_meter_no = fields.Char(string='cust_meter_no')
    

class Customers(models.Model):
    _name = 'callback.model'
    cust_parent = fields.Many2one('res.partner',ondelete='cascade')
     
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    cust_building = fields.Many2one('res.partner',ondelete='cascade')
    cust_category = fields.Char(string='Customer category')
    cust_nature_of_business = fields.Char(string='Nature of Business')
    cust_legallity = fields.Char(string='Customer legality')
    cust_name = fields.Char(string='Customer Name')
    cust_phone = fields.Char(string='Customer Phone')
    cust_email = fields.Char(string='Customer Email')
    cust_occupation = fields.Char(string='Occupation')
    cust_present_tariff = fields.Char(string='Present Tarrif')
    cust_recommended_tariff = fields.Char(string='Recommended Tariff')
    cust_estimated_load = fields.Char(string='Estimated Load')
    cust_supply_type = fields.Char(string='Supply Type')
    cust_account_no = fields.Char(string='Account Number')
    cust_has_meter = fields.Char(string='Has Meter')
    cust_meter_no = fields.Char(string='Meter Number')
    cust_meter_category = fields.Char(string='Meter Category')
    cust_meter_make = fields.Char(string='Meter Make')
    cust_type = fields.Char(string='Customer Type')
    cust_meter_type = fields.Char(string='Meter Type')
    cust_meter_sealed = fields.Char(string='Meter Sealed')
    cust_meter_status = fields.Char(string='Meter Status')
    cust_meter_accessible = fields.Char(string='Meter Accessible')
    cust_meter_location = fields.Char(string='Meter Location')
    cust_most_important_challenge = fields.Char(string='Most important challenge')
    cust_supply_time_slot = fields.Char(string='Supply Time Slot')
    cust_bill_reciept_option = fields.Char(string='Bill Receipt Option')
    cust_bill_payment_option = fields.Char(string='Bill Payment Option')
    cust_any_other_remark = fields.Char(string='Any Other Remark')
    cust_paid_for_meter = fields.Char(string='Paid For Meter')
    cust_meter_payment_evidence = fields.Char(string='Meter Payment Evidence')
    cust_bill_name = fields.Char(string='Bill Name')
    cust_title = fields.Char(string='Customer Title')
    cust_pays_estimated_bill = fields.Char(string='Pays Estimated Bill')
    cust_connection_status = fields.Char(string='Connection Status')
    cust_othernames = fields.Char(string='Othernames')
    cust_middle_name = fields.Char(string='Middle Name')
    cust_gender = fields.Char(string='Gender')
    cust_marital_status = fields.Char(string='Marital Status')
    cust_has_account_no = fields.Char(string='Has Account no')
    cust_group = fields.Char(string='Group')
    cust_has_meter_no = fields.Char(string='Has Meter No')
    cust_phase_connected = fields.Char(string='Phase Connected')
    cust_sub_class_of_business = fields.Char(string='Business Sub-Class')
    
    
class DistributionSubstation11kv_415v(models.Model):
    
    _name = 'distribution_substation_11kv_415.model'
    dss_11kv_415v_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode') 
    dss_11kv_415v_owner  = fields.Char(string='Dss 11kv_415v Owner') 
    dss_11kv_415v_name  = fields.Char(string='Dss 11kv_415v Name') 
    dss_11kv_415v_address  = fields.Char(string='Dss 11kv_415v Address') 
    dss_11kv_415v_rating  = fields.Char(string='Dss 11kv_415v Rating') 
    dss_11kv_415v_make  = fields.Char(string='Dss 11kv_415v Make') 
    dss_11kv_415v_feederpillarr_type  = fields.Char(string='FeedPillar Type') 
    dss_11kv_415v_fp_condition  = fields.Char(string='Dss 11kv_415v Fp Condition')
    dss_11kv_415v_fp_catridge  = fields.Char(string='Dss 11kv_415v Fp Catridge') 
    dss_11kv_415v_hv_fuse  = fields.Char(string='Hv Fuse')
    dss_11kv_415v_hv_fus_condition  = fields.Char(string='Hv Fus Condition') 
    dss_11kv_415v_lightning_arrester  = fields.Char(string='Lightning Arrester')  
    dss_11kv_415v_serial_no  = fields.Char(string='Serial No') 
    dss_11kv_415v_voltage_ratio  = fields.Char(string='Voltage Ratio')  
    dss_11kv_415v_oil_temp  = fields.Char(string='Oil temperature') 
    dss_11kv_415v_winding_temp  = fields.Char(string='Winding Temp') 
    dss_11kv_415v_manufacture_year  = fields.Integer(string='Manufacture Year') 
    dss_11kv_415v_installation_year  = fields.Integer(string='Installation Year') 
    dss_11kv_415v_country_of_manufacture  = fields.Char(string='Country of Manufacture') 
    dss_11kv_415v_percentage_loading  = fields.Char(string='Percentage Loading') 
    dss_11kv_415v_no_load_loss  = fields.Char(string='No Load Loss') 
    dss_11kv_415v_load_loss  = fields.Char(string='Load Loss') 
    dss_11kv_415v_impedence  = fields.Char(string='Impedance') 
    dss_11kv_415v_upriser_number = fields.Integer(string='Upriser Number') 
    dss_11kv_415v_oil_level  = fields.Char(string='Oil level')  
    dss_11kv_415v_silica_condition  = fields.Char(string='Silica Condition')  
    dss_11kv_415v_security  = fields.Char(string='Security')   
    dss_11kv_415v_substation_gravelled  = fields.Char(string='Substation Gravelled') 
    dss_11kv_415v_substation_vegetation  = fields.Char(string='Substation Vegetation') 
    dss_11kv_415v_low_voltage_cable_size  = fields.Char(string='Low voltage cable size') 
    dss_11kv_415v_is_tranformer_leaking_oil  = fields.Char(string='Transformer Leaking Oil')
    dss_11kv_415v_number_of_hv_fuse = fields.Integer(string='Number of Hv Fuse') 
    dss_11kv_415v_feederpillar_available  = fields.Char(string='Feederpillar Available') 
    dss_11kv_415v_placement  = fields.Char(string='Placement')
    dss_11kv_415v_cus_profile  = fields.Char(string='Customer Profile')
    dss_11kv_415v_red_line  = fields.Char(string='Red line')
    dss_11kv_415v_yellow_line  = fields.Char(string='Yelow Line')
    dss_11kv_415v_blue_line  = fields.Char(string='Blue Line')
    dss_11kv_415v_neutral_line  = fields.Char(string='Neutral Line')
    dss_11kv_415v_percent  = fields.Char(string='Percentage')
    dss_11kv_415v_omage  = fields.Char(string='Image')
    dss_11kv_415v_mounting  = fields.Char(string='Mounting')
    dss_11kv_415v_fp_with_meter  = fields.Char(string='Fp with meter')
    dss_11kv_415v_cooling_type  = fields.Char(string='Cooloing Type')
    dss_11kv_415v_terminal_arrangement  = fields.Char(string='Terminal Arrangement')
    dss_11kv_415v_trenches_available  = fields.Char(string='Trenches Available') 
    dss_11kv_415v_trenches_with_granite  = fields.Char(string='Trenches With Granite') 
    dss_11kv_415v_fence_type  = fields.Char(string='Fence Type') 
    

class DistributionSubstation33kv_415v(models.Model):
    
    _name = 'distribution_substation_33kv_415.model'
    dss_33kv_415v_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode') 
    dss_33kv_415v_owner  = fields.Char(string='Dss 33kv_415v Owner') 
    dss_33kv_415v_name  = fields.Char(string='Dss 33kv_415v Name') 
    dss_33kv_415v_address  = fields.Char(string='Dss 33kv_415v Address') 
    dss_33kv_415v_rating  = fields.Char(string='Dss 33kv_415v Rating') 
    dss_33kv_415v_make  = fields.Char(string='Dss 33kv_415v Make') 
    dss_33kv_415v_feederpillarr_type  = fields.Char(string='FeedPillar Type') 
    dss_33kv_415v_fp_condition  = fields.Char(string='Dss 33kv_415v Fp Condition')
    dss_33kv_415v_fp_catridge  = fields.Char(string='Dss 33kv_415v Fp Catridge') 
    dss_33kv_415v_hv_fuse  = fields.Char(string='Hv Fuse')
    dss_33kv_415v_hv_fus_condition  = fields.Char(string='Hv Fus Condition') 
    dss_33kv_415v_lightning_arrester  = fields.Char(string='Lightning Arrester')  
    dss_33kv_415v_serial_no  = fields.Char(string='Serial No') 
    dss_33kv_415v_voltage_ratio  = fields.Char(string='Voltage Ratio')  
    dss_33kv_415v_oil_temp  = fields.Char(string='Oil temperature') 
    dss_33kv_415v_winding_temp  = fields.Char(string='Winding Temp') 
    dss_33kv_415v_manufacture_year  = fields.Integer(string='Manufacture Year') 
    dss_33kv_415v_installation_year  = fields.Integer(string='Installation Year') 
    dss_33kv_415v_country_of_manufacture  = fields.Char(string='Country of Manufacture') 
    dss_33kv_415v_percentage_loading  = fields.Char(string='Percentage Loading') 
    dss_33kv_415v_no_load_loss  = fields.Char(string='No Load Loss') 
    dss_33kv_415v_load_loss  = fields.Char(string='Load Loss') 
    dss_33kv_415v_impedence  = fields.Char(string='Impedance') 
    dss_33kv_415v_upriser_number = fields.Integer(string='Upriser Number') 
    dss_33kv_415v_oil_level  = fields.Char(string='Oil level')  
    dss_33kv_415v_silica_condition  = fields.Char(string='Silica Condition')  
    dss_33kv_415v_security  = fields.Char(string='Security')   
    dss_33kv_415v_substation_gravelled  = fields.Char(string='Substation Gravelled') 
    dss_33kv_415v_substation_vegetation  = fields.Char(string='Substation Vegetation') 
    dss_33kv_415v_low_voltage_cable_size  = fields.Char(string='Low voltage cable size') 
    dss_33kv_415v_is_tranformer_leaking_oil  = fields.Char(string='Transformer Leaking Oil')
    dss_33kv_415v_number_of_hv_fuse = fields.Integer(string='Number of Hv Fuse') 
    dss_33kv_415v_feederpillar_available  = fields.Char(string='Feederpillar Available') 
    dss_33kv_415v_placement  = fields.Char(string='Placement')
    dss_33kv_415v_cus_profile  = fields.Char(string='Customer Profile')
    dss_33kv_415v_red_line  = fields.Char(string='Red line')
    dss_33kv_415v_yellow_line  = fields.Char(string='Yelow Line')
    dss_33kv_415v_blue_line  = fields.Char(string='Blue Line')
    dss_33kv_415v_neutral_line  = fields.Char(string='Neutral Line')
    dss_33kv_415v_percent  = fields.Char(string='Percentage')
    dss_33kv_415v_omage  = fields.Char(string='Image')
    dss_33kv_415v_mounting  = fields.Char(string='Mounting')
    dss_33kv_415v_fp_with_meter  = fields.Char(string='Fp with meter')
    dss_33kv_415v_cooling_type  = fields.Char(string='Cooloing Type')
    dss_33kv_415v_terminal_arrangement  = fields.Char(string='Terminal Arrangement')
    dss_33kv_415v_trenches_available  = fields.Char(string='Trenches Available') 
    dss_33kv_415v_trenches_with_granite  = fields.Char(string='Trenches Available') 
    dss_33kv_415v_fence_type  = fields.Char(string='Fence Type') 
    
    
class HighTensionPole11KV(models.Model):
    _name = 'high_tension_pole_11kv.model'
    ht_11kv_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode') 
    ht_11kv_pole_status = fields.Char(string='Pole Status')
    ht_11kv_pole_type = fields.Char(string='Pole Type') 
    ht_11kv_pole_material = fields.Char(string='Pole Material')
    ht_11kv_aluminium_conductor = fields.Char(string='Aluminium Conductor')
    ht_11kv_aluminium_size = fields.Char(string='Aluminium Size') 
    ht_11kv_overhead_sagging = fields.Char(string='Overhead Sagging')
    ht_11kv_jumper_spindle = fields.Char(string='Jumper Spindle') 
    ht_11kv_ug_length = fields.Char(string='Ug length') 
    ht_11kv_ug_size = fields.Char(string='Ug size') 
    ht_11kv_pole_stay = fields.Char(string='Pole Stay') 
    ht_11kv_bracket_post_insulator_mount = fields.Char(string='Bracket Post Insulator')
    ht_11kv_crossarm = fields.Char(string='Crossarm')
    ht_11kv_crossarm_type = fields.Char(string='Crossarm Type')
    ht_11kv_crossarm_status = fields.Char(string='Crossarm Status')
    ht_11kv_earthing = fields.Char(string='Earthing') 
    ht_11kv_no_of_pin_insulator_present = fields.Char(string='No of Pin Insulators')
    ht_11kv_insulator_type = fields.Char(string='Insulator Type')
    ht_11kv_insulator_condition = fields.Char(string='Insulator Condition')
    ht_11kv_interconnector_cable_length= fields.Char(string='Cable Length')
    ht_11kv_interconnector_cable_type = fields.Char(string='Interconnector Cable Type')
    ht_11kv_line_isolator = fields.Char(string='Line Insulator')
    ht_11kv_insulator_support = fields.Char(string='Insulator Support')
    ht_11kv_insulator_support_type = fields.Char(string='Insulator Support Type')
    ht_11kv_insulator_support_status = fields.Char(string='Insulator Support Status')
    ht_11kv_supporting_insulator_type = fields.Char(string='Supporting Insulator Type')
    ht_11kv_aluminium_cond_has_multiple_sizes = fields.Char(string='Aluminium cond multiple sizes')
    ht_11kv_aluminium_dominant_size = fields.Char(string='Aluminium Dominant Size')
    ht_11kv_aluminium_starting_size = fields.Char(string='Aluminium Starting Size')
    ht_11kv_aluminium_ending_size = fields.Char(string='Aluminium Ending Size')
    ht_11kv_circuit_type = fields.Char(string='Circuit Type')
    ht_11kv_pole_height = fields.Char(string='Pole Height')
    ht_11kv_interconnector_cable = fields.Char(string='Interconnector cable')
    ht_11kv_line_isolator_condition = fields.Char(string='Line Isolator Condition')
    ht_11kv_sectionalizer = fields.Char(string='Sectionalizer')
    ht_11kv_sectionalizer_status = fields.Char(string='Sectionalizer Status')
    ht_11kv_auto_ranger = fields.Char(string='Auto Ranger')
    ht_11kv_auto_ranger_status = fields.Char(string='Auto Ranger Status')
    ht_11kv_post_insulator_available = fields.Integer(string='Post Insulator Available') 
    ht_11kv_rmuserial = fields.Char(string='RMUSerial')
    ht_11kv_rmuyearofmanufacture = fields.Char(string='RMU Year of Manufacture')
    ht_11kv_rmu_make = fields.Char(string='RMU Make')
    ht_11kv_rmu_country_of_manufacture= fields.Char(string='RMU Country of Manufacture')
    ht_11kv_rmu_type = fields.Char(string='RMU type')
    ht_11kv_street = fields.Char(string='Street')
    ht_11kv_remark = fields.Char(string='Remark')
    ht_11kv_right_of_way_compromised = fields.Char(string='Right of way compromised') 



class HighTensionPole33KV(models.Model):
    
    _name = 'high_tension_pole_33kv.model'
    ht_33kv_parent = fields.Many2one('res.partner',ondelete='cascade')
     
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode') 
    ht_33kv_pole_status = fields.Char(string='Pole Status')
    ht_33kv_pole_type = fields.Char(string='Pole Type') 
    ht_33kv_pole_material = fields.Char(string='Pole Material')
    ht_33kv_aluminium_conductor = fields.Char(string='Aluminium Conductor')
    ht_33kv_aluminium_size = fields.Char(string='Aluminium Size') 
    ht_33kv_overhead_sagging = fields.Char(string='Overhead Sagging')
    ht_33kv_jumper_spindle = fields.Char(string='Jumper Spindle') 
    ht_33kv_ug_length = fields.Char(string='Ug length') 
    ht_33kv_ug_size = fields.Char(string='Ug size') 
    ht_33kv_pole_stay = fields.Char(string='Pole Stay') 
    ht_33kv_bracket_post_insulator_mount = fields.Char(string='Bracket Post Insulator')
    ht_33kv_crossarm = fields.Char(string='Crossarm')
    ht_33kv_crossarm_type = fields.Char(string='Crossarm Type')
    ht_33kv_crossarm_status = fields.Char(string='Crossarm Status')
    ht_33kv_earthing = fields.Char(string='Earthing') 
    ht_33kv_no_of_pin_insulator_present = fields.Char(string='No of Pin Insulators')
    ht_33kv_insulator_type = fields.Char(string='Insulator Type')
    ht_33kv_insulator_condition = fields.Char(string='Insulator Condition')
    ht_33kv_interconnector_cable_length= fields.Char(string='Cable Length')
    ht_33kv_interconnector_cable_type = fields.Char(string='Interconnector Cable Type')
    ht_33kv_line_isolator = fields.Char(string='Line Insulator')
    ht_33kv_insulator_support = fields.Char(string='Insulator Support')
    ht_33kv_insulator_support_type = fields.Char(string='Insulator Support Type')
    ht_33kv_insulator_support_status = fields.Char(string='Insulator Support Status')
    ht_33kv_supporting_insulator_type = fields.Char(string='Supporting Insulator Type')
    ht_33kv_aluminium_cond_has_multiple_sizes = fields.Char(string='Aluminium cond multiple sizes')
    ht_33kv_aluminium_dominant_size = fields.Char(string='Aluminium Dominant Size')
    ht_33kv_aluminium_starting_size = fields.Char(string='Aluminium Starting Size')
    ht_33kv_aluminium_ending_size = fields.Char(string='Aluminium Ending Size')
    ht_33kv_circuit_type = fields.Char(string='Circuit Type')
    ht_33kv_pole_height = fields.Char(string='Pole Height')
    ht_33kv_interconnector_cable = fields.Char(string='Interconnector cable')
    ht_33kv_line_isolator_condition = fields.Char(string='Line Isolator Condition')
    ht_33kv_sectionalizer = fields.Char(string='Sectionalizer')
    ht_33kv_sectionalizer_status = fields.Char(string='Sectionalizer Status')
    ht_33kv_auto_ranger = fields.Char(string='Auto Ranger')
    ht_33kv_auto_ranger_status = fields.Char(string='Auto Ranger Status')
    ht_33kv_post_insulator_available = fields.Integer(string='Post Insulator Available') 
    ht_33kv_rmuserial = fields.Char(string='RMUSerial')
    ht_33kv_rmuyearofmanufacture = fields.Char(string='RMU Year of Manufacture')
    ht_33kv_rmu_make = fields.Char(string='RMU Make')
    ht_33kv_rmu_country_of_manufacture= fields.Char(string='RMU Country of Manufacture')
    ht_33kv_rmu_type = fields.Char(string='RMU type')
    ht_33kv_street = fields.Char(string='Street')
    ht_33kv_remark = fields.Char(string='Remark')
    ht_33kv_right_of_way_compromised = fields.Char(string='Right of way compromised') 
    
    
class Incidents(models.Model):
    
    _name = 'incidents.model'
    
    incidentid = fields.Char(string='Incident id')
    assetid = fields.Char(string='Asset id')
    incident_datetime = fields.Char(string='Incident Datetime')
    incident_nature = fields.Char(string='Incident Nature')
    incident_materials = fields.Char(string='Incident Materials')
    incident_any_other_additional_information = fields.Char(string='Additional Information')
    incident_address = fields.Char(string='Incident Address')
    incident_energy_estimate = fields.Char(string='Incident Energy Estimate')
    incident_resolved = fields.Char(string='Incident Resolved')
    incident_resolved_datetime = fields.Char(string='Incident Resolved Datetime')
    date_entered = fields.Char(string='Date Entered')
    capture_latitude = fields.Float(string='Capture Latitude')
    capture_longtitude = fields.Float(string='Capture Longitude')
    capture_gps_accuracy = fields.Integer(string='Capture Gps Accuracy')
    capture_source_gps_datetime = fields.Char(string='Capture Source Gps Datetime')
    device_gps_datetime = fields.Char(string='Device Gps Datetime')
    incident_staff_distance = fields.Float(string='Incident Staff distance')
    incident_staff_device_type = fields.Char(string='Incident Staff Device Type')
    
    
class InjectionSubStation(models.Model):
    
    _name = 'iss.model'
    iss_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    iss_regional_name = fields.Char(string='Regional Name') 
    iss_business_name = fields.Char(string='Business Name')
    iss_name = fields.Char(string='IIS Name')
    iss_address = fields.Char(string='IIS Address')
    iss_ratings = fields.Char(string='IIS Ratings')
    iss_serial = fields.Char(string='IIS Serial')
    iss_make = fields.Char(string='IIS Make')
    iss_year_manufactured = fields.Integer(string='IIS Year Manufactured') 
    iss_country_of_manufacture = fields.Char(string='IIS Country of Manufacture')
    iss_cb_type = fields.Char(string='IIS CB Type')
    iss_33kv_voltage = fields.Char(string='IIS 33kv Voltage')
    iss_33kv_current = fields.Char(string='IIS 33kv Current')
    iss_outdoor_current_transformer_ratio= fields.Char(string='IIS Outdoor Current Transformer Ratio')
    iss_isolator_condition = fields.Char(string='IIS Isolator Condition') 
    iss_33kv_arrestors = fields.Char(string='IIS 33kv Arrestors') 
    iss_auxillary = fields.Char(string='IIS Auxillary') 
    iss_volatageratio = fields.Char(string='IIS Voltage Ratio') 
    iss_vectorgroup = fields.Char(string='IIS Vector Group') 
    iss_impedance = fields.Char(string='IIS Impedance')
    iss_year_commission = fields.Integer(string='IIS Year of Commission')
    iss_110v_battery_charger_type = fields.Char(string='IIS 110v Battery Charger Type')
    iss_110v_battery_charger_make = fields.Char(string='IIS 110v Battery Charger Make')
    iss_battery_bank_type = fields.Char(string='IIS Battery Bank Type')
    

class LowTensionPole(models.Model):
    
    _name = 'low_tension_pole.model'
    lt_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    lt_locality = fields.Char(string='Locality')
    lt_street = fields.Char(string='Street')
    lt_landmark= fields.Char(string='Landmark')
    lt_property = fields.Char(string='Property')
    lt_status = fields.Char(string='Status')
    lt_material = fields.Char(string='Material')
    lt_stay = fields.Char(string='Stay')
    lt_conductor = fields.Char(string='Conductor')
    lt_size_conductor = fields.Char(string='Size Conductor')
    lt_sagging = fields.Char(string='Sagging')
    lt_phases = fields.Char(string='Phases')
    lt_shakles = fields.Integer(string='Shakles')
    lt_service_cable_material = fields.Char(string='Service Cable Material')
    lt_customers = fields.Integer(string='Customers')
    lt_composite = fields.Char(string='Composite')
    
    
class Maintenance(models.Model):
    
    _name = 'maintenance.model'
    
    maintenanceid = fields.Char(string='Maintenance id')
    assetid = fields.Char(string='Asset id')
    capture_latitude = fields.Float(string='Capture Latitude')
    capture_longtitude = fields.Float(string='Capture Longitude')
    capture_gps_accuracy = fields.Integer(string='Capture GPS Accuracy')
    capture_source_gps_datetime = fields.Char(string='Capture Source GPS Datetime')
    device_gps_datetime = fields.Char(string='Device GPS Datetime')
    maintenance_staff_distance = fields.Integer(string='Maintenance Staff Distance')
    maintenance_staff_device_type = fields.Char(string='Maintenance Staff Device Type')
    maintenance_need_list = fields.Char(string='Maintenance Need List')
    maintenance_datetime = fields.Char(string='Maintenance Datetime')
    update_datetime = fields.Char(string='Update Datetime')
    
class PowerTransformer132KV_33KV (models.Model): 
    _name = 'power_transformer_132kv_33kv.model'
    pt_132kv_33kv_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    pt_132kv_33kv_name = fields.Char(string='Name') 
    pt_132kv_33kv_rating = fields.Char(string='Rating')
    
    
class PowerTransformer33KV_11KV(models.Model):
    
    _name = 'power_transformer_33KV_11KV.model'
    pt_33kv_11kv_parent = fields.Char(string='Rating')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    pt_33kv_11kv_name = fields.Char(string='Name') 
    pt_33kv_11kv_rating = fields.Char(string='Rating')
    pt_33kv_11kv_serial = fields.Char(string='Serial') 
    pt_33kv_11kv_make = fields.Char(string='Make') 
    pt_33kv_11kv_yearofmanufacture = fields.Integer(string='Year of Manufacture')
    pt_33kv_11kv_country_of_manufacture= fields.Char(string='Country of Manufacture') 
    pt_33kv_11kv_11kv_relay_make = fields.Char(string='Relay Make') 
    pt_33kv_11kv_bushingtype = fields.char(string='Brushing Type') 
    pt_33kv_11kv_primarycablesize = fields.Char(string='Primary Cable Size') 
    pt_33kv_11kv_primarycablelength = fields.Char(string='Primary Cable Length') 
    pt_33kv_11kv_secondarycablesize = fields.Char(string='Secondary Cable Size') 
    pt_33kv_11kv_secondarycablelength = fields.char(string='Secondary cable Length') 
    pt_33kv_11kv_voltage_ratio = fields.char(string='Voltage Ratio') 
    pt_33kv_11kv_vector = fields.Char(string='Vector') 
    pt_33kv_11kv_impedence = fields.Char(string='Impedance')
    pt_33kv_11kv_percentage_impedence= fields.Char(string='Percentage Impedance')
    pt_33kv_11kv_taps = fields.Integer(string='Taps')
    pt_33kv_11kv_tap_changer = fields.Char(string='Tap Changer')
    pt_33kv_11kv_oilweight = fields.Char(string='Oil Weight') 
    pt_33kv_11kv_transformerweight = fields.Char(string='Transformer Weight') 
    pt_33kv_11kv_coolingtype = fields.char(string='Cooling Type') 
    pt_33kv_11kv_transformer_oil_level = fields.Char(string='Transformer Oil Level')
    pt_33kv_11kv_silical_gel_condition = fields.Char(string='Silical Gel Condition')
    pt_33kv_11kv_trenches_available = fields.Char(string='Trenches Available')
    pt_33kv_11kv_trenches_with_granite = fields.Char(string='Trenches with Granite')
    pt_33kv_11kv_fence_type = fields.Char(string='Fence Type')
    
    
class ServiceUnits(models.Model):
    
    _name = 'service_units.model'
    
    name = fields.Char(string='Name')
    biz_hub = fields.Char(string='Business Hub')
    region = fields.Char(string='Regions')


class Staff(models.Model):
    
    _name = 'staff.model'
    
    staffid = fields.Char(string='Staff id')
    surname = fields.Char(string='Surname') 
    othernames = fields.Char(string='Othernames') 
    residential_address = fields.Char(string='Resendential Address')
    telephone = fields.Char(string='Telephone') 
    email_address = fields.Char(string='Email Address') 
    staff_category = fields.Char(string='Staff Category')
    staff_registering = fields.Char(string='Staff Registering')
    capture_datetime = fields.Char(string='Capture Datetime')
    password = fields.Binary(string='Password')
    scope = fields.Char(string='Scope') 
    scopeid = fields.Char(string='Scope id') 
    unit = fields.Char(string='Unit') 
    role = fields.Char(string='role')
    

class Upriser(models.Model):
    
    _name = 'upriser.model'
    up_parent = fields.Many2one('res.partner',ondelete='cascade')
    
    assetid	= fields.Char(string='Asset id')
    latitude = fields.Float(string='Latitude')
    longitude = fields.Float(string='Longitude')
    naccode = fields.Char(string='Naccode')
    up_cable = fields.Char(string='Up Cable')
    up_size = fields.Char(string='Up Size')
    up_length = fields.Char(string='Up Length')
    up_condition = fields.Char(string='Up Condition')


